FROM php:7.2-cli

RUN apt-get update && apt-get install -y \
    autoconf \
    graphviz \
    libicu-dev \
    wget \
    zlib1g-dev \
    # Configure PHP extensions
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-enable intl \
    # Install phpdoc utility
    && wget http://phpdoc.org/phpDocumentor.phar

# Update PHP config
COPY env/test/docker/test.ini $PHP_INI_DIR/conf.d/

ENTRYPOINT /bin/sh
