FROM php:8.1-cli-alpine

RUN pecl install xdebug-3.1.4 \
    && docker-php-ext-enable xdebug

COPY ./env/test/docker/test.ini $PHP_INI_DIR/conf.d/

COPY . /usr/src/sdk

WORKDIR /usr/src/sdk

CMD [ "php", "./run-tests.php" ]
