FROM php:7.4-cli-alpine

# 3.0.0 fails with err: Use of undefined constant XDEBUG_CC_UNUSED - assumed 'XDEBUG_CC_UNUSED' (this will throw an Error in a future version of PHP)
RUN apk add autoconf gcc build-base linux-headers \
    && pecl install xdebug-2.9.8 \
    && docker-php-ext-enable xdebug \
    && apk del autoconf gcc build-base linux-headers

COPY ./env/test/docker/test.ini $PHP_INI_DIR/conf.d/

COPY . /usr/src/sdk

WORKDIR /usr/src/sdk

CMD [ "php", "./run-tests.php" ]
