FROM php:8.2-cli-alpine

RUN apk add autoconf gcc build-base linux-headers \
    && pecl install xdebug-3.2.0 \
    && docker-php-ext-enable xdebug \
    && apk del autoconf gcc build-base linux-headers

COPY ./env/test/docker/test.ini $PHP_INI_DIR/conf.d/

COPY . /usr/src/sdk

WORKDIR /usr/src/sdk

CMD [ "php", "./run-tests.php" ]
